"use client";
import { useState, useEffect } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/navBar";
import SideBar from "./components/sideBar";
import { account } from "./appwrite/appwriteConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userDetails, setUserDetails]: any = useState();
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    const getAccount = account.get();
    getAccount.then(
      (res) => {
        setIsLoggedIn(true);
        setUserDetails(res);
      },
      (err) => console.log(err)
    );
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoggedIn ? (
          <main className="w-full h-screen bg-transparent relative before:content-[''] before:absolute before:w-full before:h-[50vh] before:-z-10 before:bottom-0 before:left-0 before:bg-[rgba(255,255,255,0.9)] p-7">
            <div className="absolute w-full -z-10 top-0 left-0 h-[50vh] bg-neutral-100"></div>

            <NavBar />
            <section className="w-full pt-4 flex gap-6">
              <SideBar />
              <div className="w-[calc(100%-239px)] h-[80vh]">{children}</div>
            </section>
          </main>
        ) : (
          <main className="w-full h-screen bg-transparent relative before:content-[''] before:absolute before:w-full before:h-[50vh] before:-z-10 before:bottom-0 before:left-0 before:bg-[rgba(255,255,255,0.9)] flex justify-center items-center">
            <div className="absolute w-full -z-10 top-0 left-0 h-[50vh] bg-neutral-100"></div>
            <div className="flex flex-col h-auto w-[330px] bg-white rounded border border-solid border-[rgba(0,0,0,0.1)] p-3">
              <p className="font-medium text-sm">
                👋 SignIn or SignUp to use Mine Cloud
              </p>
              <div className="pt-2">
                <button
                  onClick={() => {
                    account.createOAuth2Session(
                      "google",
                      "https://localhost:3000/",
                      "https://localhost:3000/"
                    );
                  }}
                >
                  Continue with Google
                </button>
              </div>
            </div>
          </main>
        )}
      </body>
    </html>
  );
}
